name = "ReversePropagation"
uuid = "527681c1-8309-4d3f-8790-caf822a419ba"
authors = ["David P. Sanders <dpsanders@gmail.com> and contributors"]
version = "0.1.0"

[deps]
ChainRules = "082447d4-558c-5d27-93f4-14fc19e9eca2"
IntervalArithmetic = "d1acc4aa-44c8-5952-acd4-ba5d80a2a253"
IntervalContractors = "15111844-de3b-5229-b4ba-526f2f385dc9"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
SymbolicUtils = "d1185830-fcd6-423d-90d6-eec64667417b"
Symbolics = "0c5d862f-8b57-4792-8d23-62f2024744c7"

[compat]
ChainRules = "0.7"
IntervalArithmetic = "0.17"
IntervalContractors = "0.4"
OrderedCollections = "1.4"
SymbolicUtils = "0.8, 0.9, 0.10"
Symbolics = "0.1"
julia = "1.5, 1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
